name: CleanUpDevDeployment
on:
  # Trigger the workflow on PR Close
  pull_request:
    types:
      - closed

jobs:
  clean_up_static_deployment:
    # for more informaiton about the `runs-on` keyword please see:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
    - name: Print Branch Name Target
      run: echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
    - name: Create empty directory
      run: mkdir empty-directory
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: hello-static.ussba.io-static-content
        AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'empty-directory'
        DEST_DIR: "${GITHUB_HEAD_REF}"
    - uses: mshick/add-pr-comment@v1
      with:
        message: "🧹 Cleaned up static deployment for `/${{ github.head_ref }}/*`"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false
