name: DeployToDev
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  #push:
  #  branches:
  #    - main
  pull_request:
    branches:
      - main

jobs:
  deploy_static:
    # for more informaiton about the `runs-on` keyword please see:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print Branch Name Target
      run: echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: disaster-loan.ussba.io-static-content
        AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'
        DEST_DIR: "${GITHUB_HEAD_REF}"
    - uses: mshick/add-pr-comment@v1
      with:
        message: "👀 Preview deployment is now available - https://hello-static.ussba.io/${{ github.head_ref }}/index.html"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false
